default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  database: <%= Figaro.env.db_name %>
  username: <%= Figaro.env.db_username %>
  password: <%= Figaro.env.db_password %>
  host: <%= Figaro.env.db_host %>
  port: <%= Figaro.env.db_port %>

development:
  <<: *default

test:
  <<: *default

playground:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
