# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a018f7d285bdd6a67717ed39e5858abc6a885ebb6fb757154e901b6f710ab8cdb8b985d874137ab58cfa496484d0099b7c3ff36cb0a0b3f473fa390ee977998

test:
  secret_key_base: 2b182850e50b5c57d39798211807c095d9cfd0c6cb6fbbfe764c6ce9c45bf1d2f9d8931587453e1bf7211c4820b004f7707c1b2e457175cf3a443400760f8128

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
