defaults: &settings
  version: 0.12.7
  app_name: Zazo Renotification Service
  app_name_key: renotification

  app_key: zazo-renotification
  app_env: zrn-production

  test_phone: '+16502453537'
  test_email: 'elfishawy.sani@gmail.com'

development:
  <<: *settings

test:
  <<: *settings

staging:
  <<: *settings

production:
  <<: *settings
